name: GraphQL Validation
on: push
jobs:
  graphql-validate:
    runs-on: ubuntu-20.04
    steps:
      - name: set up node.js
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14.15.0
      - name: check out code
        uses: actions/checkout@v2
      - name: install deps
        run: yarn install
      - name: run codegen
        run: yarn generate